delay: 10
feeds:
- https://bsky.app/profile/did:plc:scu6k7rw2d76hencnibsvsgj/rss
- https://www.fedscoop.com/feed
- https://brobible.com/tag/memes/feed
- http://feeds.denverpost.com/dp-news-breaking
- https://krebsonsecurity.com/feed/
- https://www.merriam-webster.com/wotd/feed/rss2
- http://feeds.bbci.co.uk/news/world/rss.xml?edition=uk
- http://rss.slashdot.org/Slashdot/slashdotApple
- http://rss.slashdot.org/Slashdot/slashdotHardware
- https://www.cisa.gov/news.xml
- https://www.cisa.gov/cybersecurity-advisories/all.xml
- https://www.netresec.com/rss.ashx
- https://feeds.feedburner.com/GoogleOnlineSecurityBlog
- https://www.fedscoop.com/feed
- https://feeds2.feedburner.com/inkophile
- https://googleprojectzero.blogspot.com/feeds/posts/default
- https://www.penaddict.com/blog?format=rss
