delay: 10
feeds:
- https://www.fedscoop.com/feed
- http://feeds.denverpost.com/dp-news-breaking
- https://krebsonsecurity.com/feed/
- https://www.merriam-webster.com/wotd/feed/rss2
- http://feeds.bbci.co.uk/news/world/rss.xml?edition=uk
- http://rss.cnn.com/rss/cnn_topstories.rss
- http://rss.slashdot.org/Slashdot/slashdotApple
- http://rss.slashdot.org/Slashdot/slashdotHardware
- https://www.cisa.gov/news.xml
- https://www.cisa.gov/cybersecurity-advisories/all.xml
- https://addons.mozilla.org/en-US/developers/feed?privaterss=96cd0dc3-3a74-b43d-b5b5-c8eda8cc356f
- https://www.netresec.com/rss.ashx
- https://feeds.feedburner.com/GoogleOnlineSecurityBlog
- https://what-if.xkcd.com/feed.atom
- https://threatpost.com/feed/
- https://www.fedscoop.com/feed
- https://feeds2.feedburner.com/inkophile
- https://googleprojectzero.blogspot.com/feeds/posts/default
- https://www.wnyc.org/feeds/people/shankar-vedantam
- https://www.penaddict.com/blog?format=rss
- https://tidbits.com/feeds/tidbits_blurb.rss
