#! /bin/bash

QUOTE=$(head -1 ~/bin/quotes)
tail +2 ~/bin/quotes > $$
echo "$QUOTE" >> $$
mv $$ ~/bin/quotes

curl -s -X POST \
    --silent \
    -H 'Content-type: application/json' \
    --data '{"text":"'"$QUOTE"'"}' \
https://hooks.slack.com/services/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 > /dev/null


